title: Warren Zhu 朱富橙
email: wzhu@college.harvard.edu 
description: >- 
  I like to play around with things. Posting whilst learning :). Say hi at wzhu@college.harvard.edu.
baseurl: ""
url: "https://www.warrenzhu.com"
github_username: WarrenZhu050413

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - modes/
  - modes_backup/
  - _posts/pdf/
  - _posts_pdf_backup/
  - test-categories.html
  - .jekyll-ignore

# Collections
collections:
  notes:
    output: true
    permalink: /notes/:path/
  sentences:
    output: true
    permalink: /sentences/:slug/

# Default layouts for collections
defaults:
  - scope:
      path: ""
      type: sentences
    values:
      layout: sentence

# Author information
author:
  name: Warren Zhu (朱富橙)
  email: wzhu@college.harvard.edu

# Minima theme settings
minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    github: WarrenZhu050413

# Scholar settings for citations
scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: .
  bibliography: _bibliography/references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
  cite_inline: true
  cite_inline_template: "[@{{key}}]"
  cite_inline_style: apa
  cite_inline_link: true
  cite_inline_link_style: apa
  cite_inline_link_template: "[@{{key}}]"
  cite_inline_link_prefix: ""
  cite_inline_link_suffix: ""
  cite_inline_reference: true
  cite_inline_reference_template: "[@{{key}}]"
  cite_inline_reference_style: apa
  cite_inline_reference_link: true
  cite_inline_reference_link_style: apa
  cite_inline_reference_link_template: "[@{{key}}]"
  cite_inline_reference_link_prefix: ""
  cite_inline_reference_link_suffix: ""

# Pagination for blog
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/ 
